# Generated by Django 3.0.6 on 2020-06-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=255, verbose_name='Cuisine')),
                ('title', models.CharField(max_length=255, verbose_name='Recipe Title')),
                ('description', models.TextField(blank=True, verbose_name='Recipe Description')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255, verbose_name='Ingredient Name')),
                ('amount_needed', models.IntegerField(default=1)),
                ('unit_measurement', models.CharField(max_length=255, verbose_name='Measurement Unit')),
                ('recipes', models.ManyToManyField(to='recipes.Recipe')),
            ],
        ),
    ]
