# Generated by Django 5.1.7 on 2025-06-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('american', 'American'), ('french', 'French'), ('italian', 'Italian'), ('spanish', 'Spanish'), ('mediterranean', 'Mediterranean'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('thai', 'Thai'), ('vietnamese', 'Vietnamese'), ('indian', 'Indian'), ('filipino', 'Filipino'), ('malaysian', 'Malaysian'), ('indonesian', 'Indonesian'), ('middle_eastern', 'Middle Eastern'), ('moroccan', 'Moroccan'), ('ethiopian', 'Ethiopian'), ('west_african', 'West African'), ('mexican', 'Mexican'), ('brazilian', 'Brazilian'), ('peruvian', 'Peruvian'), ('argentinian', 'Argentinian'), ('caribbean', 'Caribbean'), ('eastern_european', 'Eastern European'), ('russian', 'Russian'), ('polish', 'Polish')], max_length=20, null=True),
        ),
    ]
