# Generated by Django 5.2.3 on 2025-08-09 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_cuisine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('american', 'American'), ('french', 'French'), ('italian', 'Italian'), ('spanish', 'Spanish'), ('mediterranean', 'Mediterranean'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('thai', 'Thai'), ('vietnamese', 'Vietnamese'), ('indian', 'Indian'), ('filipino', 'Filipino'), ('malaysian', 'Malaysian'), ('indonesian', 'Indonesian'), ('middle_eastern', 'Middle Eastern'), ('moroccan', 'Moroccan'), ('ethiopian', 'Ethiopian'), ('west_african', 'West African'), ('mexican', 'Mexican'), ('brazilian', 'Brazilian'), ('peruvian', 'Peruvian'), ('argentinian', 'Argentinian'), ('caribbean', 'Caribbean'), ('eastern_european', 'Eastern European'), ('russian', 'Russian'), ('polish', 'Polish'), ('miscellaneous', 'Miscellaneous')], max_length=20, null=True),
        ),
    ]
