# Generated by Django 5.2.3 on 2026-04-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_prep_time_alter_recipe_cuisine"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True,
                related_name="recipes",
                through="recipes.RecipeIngredient",
                to="recipes.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cuisine",
            field=models.CharField(
                blank=True,
                choices=[
                    ("italian", "Italian"),
                    ("french", "French"),
                    ("chinese", "Chinese"),
                    ("japanese", "Japanese"),
                    ("korean", "Korean"),
                    ("american", "American"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="prep_time",
            field=models.PositiveIntegerField(
                blank=True, help_text="Time in minutes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
