# Generated by Django 5.2.3 on 2026-04-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_created_by_alter_recipe_cuisine"),
        ("recipes", "0005_recipe_ingredients_alter_recipe_cuisine_and_more"),
    ]

    operations = []
