# Generated by Django 5.2.3 on 2026-04-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_merge_20260424_0016"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
