# Generated by Django 5.2.3 on 2026-04-29 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "prep_time",
                    models.PositiveIntegerField(
                        blank=True, help_text="Time in minutes", null=True
                    ),
                ),
                ("cook_time", models.PositiveIntegerField(help_text="Time in minutes")),
                ("servings", models.PositiveIntegerField()),
                ("instructions", models.TextField()),
                (
                    "cuisine",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("american", "American"),
                            ("french", "French"),
                            ("italian", "Italian"),
                            ("spanish", "Spanish"),
                            ("mediterranean", "Mediterranean"),
                            ("chinese", "Chinese"),
                            ("japanese", "Japanese"),
                            ("korean", "Korean"),
                            ("thai", "Thai"),
                            ("vietnamese", "Vietnamese"),
                            ("indian", "Indian"),
                            ("filipino", "Filipino"),
                            ("malaysian", "Malaysian"),
                            ("indonesian", "Indonesian"),
                            ("middle_eastern", "Middle Eastern"),
                            ("moroccan", "Moroccan"),
                            ("ethiopian", "Ethiopian"),
                            ("west_african", "West African"),
                            ("mexican", "Mexican"),
                            ("brazilian", "Brazilian"),
                            ("peruvian", "Peruvian"),
                            ("argentinian", "Argentinian"),
                            ("caribbean", "Caribbean"),
                            ("eastern_european", "Eastern European"),
                            ("russian", "Russian"),
                            ("polish", "Polish"),
                            ("miscellaneous", "Miscellaneous"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=64)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="recipes.recipe",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True,
                related_name="recipes",
                through="recipes.RecipeIngredient",
                to="recipes.ingredient",
            ),
        ),
    ]
