# Generated by Django 5.1.7 on 2026-05-01 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "prep_time",
                    models.PositiveIntegerField(
                        blank=True, help_text="Time in minutes", null=True
                    ),
                ),
                ("cook_time", models.PositiveIntegerField(help_text="Time in minutes")),
                ("servings", models.PositiveIntegerField()),
                (
                    "cuisine",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("american", "American"),
                            ("french", "French"),
                            ("italian", "Italian"),
                            ("spanish", "Spanish"),
                            ("mediterranean", "Mediterranean"),
                            ("chinese", "Chinese"),
                            ("japanese", "Japanese"),
                            ("korean", "Korean"),
                            ("thai", "Thai"),
                            ("vietnamese", "Vietnamese"),
                            ("indian", "Indian"),
                            ("filipino", "Filipino"),
                            ("malaysian", "Malaysian"),
                            ("indonesian", "Indonesian"),
                            ("middle_eastern", "Middle Eastern"),
                            ("moroccan", "Moroccan"),
                            ("ethiopian", "Ethiopian"),
                            ("west_african", "West African"),
                            ("mexican", "Mexican"),
                            ("brazilian", "Brazilian"),
                            ("peruvian", "Peruvian"),
                            ("argentinian", "Argentinian"),
                            ("caribbean", "Caribbean"),
                            ("eastern_european", "Eastern European"),
                            ("russian", "Russian"),
                            ("polish", "Polish"),
                            ("miscellaneous", "Miscellaneous"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No unit"),
                            ("teaspoon(s)", "teaspoon(s)"),
                            ("tablespoon(s)", "tablespoon(s)"),
                            ("fluid ounce(s)", "fluid ounce(s)"),
                            ("cup(s)", "cup(s)"),
                            ("pint(s)", "pint(s)"),
                            ("quart(s)", "quart(s)"),
                            ("gallon(s)", "gallon(s)"),
                            ("milliliter(s)", "milliliter(s)"),
                            ("liter(s)", "liter(s)"),
                            ("ounce(s)", "ounce(s)"),
                            ("pound(s)", "pound(s)"),
                            ("gram(s)", "gram(s)"),
                            ("kilogram(s)", "kilogram(s)"),
                            ("whole", "whole"),
                            ("piece(s)", "piece(s)"),
                            ("slice(s)", "slice(s)"),
                            ("clove(s)", "clove(s)"),
                            ("sprig(s)", "sprig(s)"),
                            ("bunch(es)", "bunch(es)"),
                            ("can(s)", "can(s)"),
                            ("jar(s)", "jar(s)"),
                            ("package(s)", "package(s)"),
                            ("pinch(es)", "pinch(es)"),
                            ("dash(es)", "dash(es)"),
                            ("handful(s)", "handful(s)"),
                            ("to taste", "to taste"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="recipes.recipe",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True,
                related_name="recipes",
                through="recipes.RecipeIngredient",
                to="recipes.ingredient",
            ),
        ),
        migrations.CreateModel(
            name="RecipeInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveIntegerField()),
                (
                    "instruction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_instructions",
                        to="recipes.instruction",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_instructions",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["step_number", "id"],
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.ManyToManyField(
                blank=True,
                related_name="recipes",
                through="recipes.RecipeInstruction",
                to="recipes.instruction",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeinstruction",
            constraint=models.UniqueConstraint(
                fields=("recipe", "step_number"), name="unique_recipe_instruction_step"
            ),
        ),
    ]
