# Generated by Django 5.2.3 on 2026-05-12 08:13

import django.db.models.deletion
import recipes.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=recipes.storage_paths.recipe_gallery_image_upload_to
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_images",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recipe", "position"),
                        name="unique_recipe_image_position",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("position__gte", 0), ("position__lt", 5)),
                        name="recipe_image_position_in_range",
                    ),
                ],
            },
        ),
    ]
